#!/usr/bin/env python
import argparse
import logging
from speedtestmqtt.speedtestmqtt import SpeedTestMQTT



class VAction(argparse.Action):
    """
    Verbosity flag action. Original source:
      http://stackoverflow.com/a/6076779/5480526
    """
    def __call__(self, parser, args, values, option_string=None):
        if values == None:
            values = "1"
        try:
            values = int(values)
        except ValueError:
            values = values.count("v") + 1
        setattr(args, self.dest, values)



def prepare_parser(parser):
    parser.add_argument("--broker", type=str, default="localhost")
    parser.add_argument("--topic", type=str, default="speedtest")
    parser.add_argument("--clientid", type=str, default="speedtest")
    parser.add_argument('-v', nargs='?', action=VAction, dest="verbose")
    

def run_program(parser):
    config = vars(parser.parse_args())
    # prepare logging
    log_level = logging.ERROR
    if config["verbose"] and config["verbose"] == 1:
        log_level = logging.INFO
    elif config["verbose"] and config["verbose"] >= 2:
        log_level = logging.DEBUG
    logging.basicConfig()
    logger = logging.getLogger("speedtest-mqtt")
    logger.setLevel(log_level)
    # run
    s = SpeedTestMQTT(config["broker"],
                      mqtt_client_id=config["clientid"],
                      mqtt_topic=config["topic"],
                      log_level=log_level)
    s.start()
    
    
    
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Speedtest with MQTT interface.")
    prepare_parser(parser)
    run_program(parser)
